### ISSUE TITLE
this sortable deactive click action

### ISSUE THREAD

**Issue by 9px** [farhadi/html5sortable#103]
when i insert an input in the sortable items, the click on the text input doesn't work!
for example if the input (in the ul.sortable > li) have some text, when i click on the center of text, the cursor must go to the point, but the cursor appear in the start of text!

**Comment by voidberg** [comment]
This project has been discontinued by its author and the new mantained version is [here](http://github.com/voidberg/html5sortable).

Since the projects have diverged a while ago I can't migrate issues and pull requests. Please try the new version and if the issue or pull request still makes sense, please resubmit it.

Sorry for the inconvenience.
