### ISSUE TITLE
Blinking when dragging

### ISSUE THREAD

**Issue by alexjoverm** [farhadi/html5sortable#105]
Hi! I had the issue that when dragging the placeholder place was blinking. I've solved it changing the line 58:

```javascript
).end().add([this, placeholder]).on('dragover.h5s dragenter.h5s drop.h5s', function(e) {
```

to:
```javascript
).end().add([this, placeholder[0]]).on('dragover.h5s dragenter.h5s drop.h5s', function(e) {
```

This is due to the `.add` method need javascript objects instead of jquery objects, and placeholder was a jquery object.

I don't know if this has happened before, was strange. Anyway, I just wanted to contribute in case any other experience the same.

Just to know more data, I'm using jquery 2.1.0, and the element I'm applying the sortable has the following structure:

```html 
<ul>
     <li >
           <img src="" alt="">
           <div class="first-row"><b>...</b> ....</div>
           <div class="second-row">...<i>....</i></div>
      </li>

      .....
</ul>
```

**Comment by voidberg** [comment]
This project has been discontinued by its author and the new mantained version is [here](http://github.com/voidberg/html5sortable).

Since the projects have diverged a while ago I can't migrate issues and pull requests. Please try the new version and if the issue or pull request still makes sense, please resubmit it.

Sorry for the inconvenience.
