### ISSUE TITLE
Two draggable elements in one position

### ISSUE THREAD

**Issue by elchiconube** [farhadi/html5sortable#107]
Hi, I want to know If it's possible to put two draggable elements in the same position. For example, I need to drag two events to the same day in a calendar.

Thanks :)

**Comment by voidberg** [comment]
This project has been discontinued by its author and the new mantained version is [here](http://github.com/voidberg/html5sortable).

Since the projects have diverged a while ago I can't migrate issues and pull requests. Please try the new version and if the issue or pull request still makes sense, please resubmit it.

Sorry for the inconvenience.
